# Generated by Django 4.1.3 on 2022-11-23 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentesSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=250)),
                ('personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periodo', models.CharField(choices=[('1', '1 mes'), ('2', '2 meses'), ('3', '3 meses'), ('4', '4 meses'), ('5', '5 meses'), ('6', '6 meses'), ('+6', '+6 meses')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_postal', models.IntegerField()),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('cod_area', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medio_cotizacion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AutoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AutoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1953)])),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
                ('uso', models.CharField(choices=[('P', 'Personal'), ('C', 'Comercial')], max_length=25)),
                ('gnc', models.BooleanField()),
                ('cero_km', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BiciSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2017)])),
                ('marca_modelo', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('MB', 'Mountain Bike'), ('R', 'Rutera'), ('BMX', 'BMX'), ('P', 'Paseo')], max_length=25)),
                ('valor', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('AC', 'Acero'), ('AL', 'Aluminio'), ('CA', 'Carbon'), ('TI', 'Titanio')], max_length=25)),
                ('rodado', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CamionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CamionSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1953)])),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
                ('radio', models.CharField(choices=[('U', 'Urbano'), ('N', 'Nacional')], max_length=25)),
                ('gnc', models.BooleanField()),
                ('cero_km', models.BooleanField()),
                ('acoplado', models.BooleanField()),
                ('marca_modelo_acoplado', models.CharField(max_length=250)),
                ('anio_acoplado', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1953)])),
            ],
        ),
        migrations.CreateModel(
            name='CaucionSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('suma_asegurada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ComercioSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('construccion', models.CharField(max_length=250)),
                ('material_techo', models.CharField(max_length=250)),
                ('m2', models.IntegerField()),
                ('valor', models.FloatField()),
                ('rejas', models.CharField(max_length=250)),
                ('linderos', models.CharField(choices=[('SB', 'Sin baldio'), ('BA', 'Baldio abandonado'), ('BM', 'Baldio con medianera')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FlotaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='HogarSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construccion', models.CharField(max_length=250)),
                ('material_techo', models.CharField(max_length=250)),
                ('m2', models.IntegerField()),
                ('valor', models.FloatField()),
                ('rejas', models.CharField(max_length=250)),
                ('linderos', models.CharField(choices=[('SB', 'Sin baldio'), ('BA', 'Baldio abandonado'), ('BM', 'Baldio con medianera')], max_length=25)),
                ('tipo_bici', models.CharField(choices=[('RDYF', 'Robo dentro y fuera del domicilio'), ('NO', 'No agrego bicicleta'), ('AMBOS', 'Cotizar ambos presupuestos')], max_length=40)),
                ('marca_modelo_bici', models.CharField(max_length=250)),
                ('valor_bici', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonopatinSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2017)])),
                ('marca_modelo', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('B', 'Bateria'), ('E', 'Electrico')], max_length=25)),
                ('valor', models.FloatField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MotoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970)])),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
                ('uso', models.CharField(choices=[('P', 'Personal'), ('C', 'Comercial')], max_length=25)),
                ('cero_km', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PraxisMedicaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VidaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('V', 'Vida'), ('S', 'Sepelio')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=250)),
                ('data_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.account')),
            ],
        ),
        migrations.CreateModel(
            name='AutoFlotaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1953)])),
                ('modelo', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=250)),
                ('uso', models.CharField(choices=[('P', 'Personal'), ('C', 'Comercial')], max_length=25)),
                ('gnc', models.BooleanField()),
                ('cero_km', models.BooleanField()),
                ('flota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.flotaseguro')),
            ],
        ),
    ]
