# Generated by Django 4.1.3 on 2022-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoflotaseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='autoseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='biciseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='camionseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='camionseguro',
            old_name='anio_acoplado',
            new_name='año_acoplado',
        ),
        migrations.RenameField(
            model_name='monopatinseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='motoseguro',
            old_name='anio',
            new_name='año',
        ),
        migrations.AlterField(
            model_name='account',
            name='cod_area',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='cod_postal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='medio_cotizacion',
            field=models.CharField(choices=[('WP', 'WhatsApp'), ('LL', 'LLamado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
