# Generated by Django 4.1.3 on 2022-11-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0002_rename_anio_autoflotaseguro_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseguro',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userseguro',
            name='uuid',
            field=models.CharField(default='c303282d-f2e6-46ca-a04a-35d3d873712d', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userseguro',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguros.account'),
        ),
    ]
